#eureka details
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance.hostname:localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    username: root
    password: root
  jpa:
    genrate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
